// frontend/src/app/layout.tsx
// import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext"; //for dark - light theme
import { ThemeWrapper } from "./components/ThemeWrapper";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" suppressHydrationWarning>
    <ThemeProvider>
      <ThemeWrapper>
        {children}
      </ThemeWrapper>
    </ThemeProvider>
  </html>
  );
}
